### ISSUE TITLE
prov/verbs: Atomic `FI_CSWAP` broken when using `FI_EP_MSG`

### ISSUE THREAD

**Issue by youtive10** [ofiwg/libfabric#10911]
**Describe the bug**
When performing the `FI_CSWAP` operation using `fi_compare_atomic()` with an `FI_EP_MSG` and Infiniband, the swap is not performed and the endianness of the received result is reversed (see minimal example below).
I've also used the `fi_compare_atomicvalid()` to confirm that the `FI_CSWAP` operation is supported.

However, when using the same approach shown in the minimal example while using an `FI_EP_RDM` endpoint, the `FI_CSWAP` operation is executed as expected.

**To Reproduce**
This is a broken down version of the actual code.

On target side:
```C
uint64_t *buffer = calloc(sizeof(uint64_t) * 32);
buffer[0] = 516;
// buffer will be registered using fi_mr_reg with FI_WRITE | FI_REMOTE_WRITE | FI_READ | FI_REMOTE_READ
// ... the keys and buffer address will be exchanged
// after the atomic operation on initiator side completed:
for (uint64_t i = 0; i < 3; i++) {
	std::cout << i << ": " << buffer[i] << endl;
}
```

On initiator side:
```C++
uint64_t *buffer = calloc(sizeof(uint64_t) * 32);
buffer[0] = 0;
buffer[1] = 516;
buffer[2] = 0;
// buffer will be registered using fi_mr_reg with FI_WRITE | FI_REMOTE_WRITE | FI_READ | FI_REMOTE_READ
// ... the keys and buffer address will be exchanged
// after operation completed...
int ret = fi_compare_atomic(
	ep,
	buffer,
	1,
	fi_mr_desc(buffer_fid_mr_),
	buffer + 1,
	fi_mr_desc(buffer_fid_mr_),
	buffer + 2,
	fi_mr_desc(buffer_fid_mr_),
	0,
	remote_buffer_address,
	remote_buffer_key,
	FI_UINT64,
	FI_CSWAP,
	ctx
);
// ret is checked to be FI_SUCCESS
// after operation completed...
for (uint64_t i = 0; i < 3; i++) {
	std::cout << i << ": " << buffer[i] << endl;
}
```

**For `FI_EP_MSG`:**
Output on initiator:
```
0: 0
1: 516
2: 288793326105133056
```
Output on target:
```
0: 516
1: 0
2: 0
```

**For `FI_EP_RDM`:**
Output on initiator:
```
0: 0
1: 516
2: 516
```
Output on target:
```
0: 0
1: 0
2: 0
```

`fi_info` used to initialize the `FI_EP_MSG` endpoint:
```
fi_info:
    caps: [ FI_RMA, FI_ATOMIC, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_LOCAL_COMM, FI_REMOTE_COMM ]
    mode: [ FI_RX_CQ_DATA ]
    addr_format: FI_SOCKADDR_IN
    src_addrlen: 16
    dest_addrlen: 16
    src_addr: fi_sockaddr_in://<removed>:0
    dest_addr: fi_sockaddr_in://<removed>:8080
    handle: (nil)
    fi_tx_attr:
        caps: [ FI_RMA, FI_ATOMIC, FI_READ, FI_WRITE, FI_SEND ]
        mode: [  ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_RMA_RAR, FI_ORDER_RMA_RAW, FI_ORDER_RMA_WAW, FI_ORDER_ATOMIC_RAR, FI_ORDER_ATOMIC_RAW, FI_ORDER_ATOMIC_WAW ]
        inject_size: 256
        size: 384
        iov_limit: 4
        rma_iov_limit: 1
        tclass: 0x0
    fi_rx_attr:
        caps: [ FI_RMA, FI_ATOMIC, FI_RECV, FI_REMOTE_READ, FI_REMOTE_WRITE ]
        mode: [ FI_RX_CQ_DATA ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_RMA_RAR, FI_ORDER_RMA_RAW, FI_ORDER_RMA_WAW, FI_ORDER_ATOMIC_RAR, FI_ORDER_ATOMIC_RAW, FI_ORDER_ATOMIC_WAW ]
        size: 384
        iov_limit: 4
    fi_ep_attr:
        type: FI_EP_MSG
        protocol: FI_PROTO_RDMA_CM_IB_RC
        protocol_version: 1
        max_msg_size: 1073741824
        msg_prefix_size: 0
        max_order_raw_size: 1073741824
        max_order_war_size: 0
        max_order_waw_size: 1073741824
        mem_tag_format: 0x0000000000000000
        tx_ctx_cnt: 1
        rx_ctx_cnt: 1
        auth_key_size: 0
    fi_domain_attr:
        domain: 0x0
        name: ibp202s0
        threading: FI_THREAD_SAFE
        progress: FI_PROGRESS_AUTO
        resource_mgmt: FI_RM_ENABLED
        av_type: FI_AV_UNSPEC
        mr_mode: [ FI_MR_LOCAL, FI_MR_VIRT_ADDR, FI_MR_ALLOCATED, FI_MR_PROV_KEY ]
        mr_key_size: 4
        cq_data_size: 4
        cq_cnt: 16777216
        ep_cnt: 131072
        tx_ctx_cnt: 1024
        rx_ctx_cnt: 1024
        max_ep_tx_ctx: 1024
        max_ep_rx_ctx: 1024
        max_ep_stx_ctx: 0
        max_ep_srx_ctx: 8388608
        cntr_cnt: 0
        mr_iov_limit: 1
        caps: [ FI_LOCAL_COMM, FI_REMOTE_COMM ]
        mode: [  ]
        auth_key_size: 0
        max_err_data: 255
        mr_cnt: 16777216
        tclass: 0x0
    fi_fabric_attr:
        name: IB-0xfe80000000000000
        prov_name: verbs
        prov_version: 201.0
        api_version: 2.1
    nic:
        fi_device_attr:
            <removed>
        fi_bus_attr:
            bus_type: FI_BUS_UNKNOWN
        fi_link_attr:
            address: (null)
            mtu: 4096
            speed: 100000000000
            state: FI_LINK_UP
            network_type: InfiniBand
```

`fi_info` of the `FI_EP_RDM` endpoint:
```
fi_info:
    caps: [ FI_RMA, FI_ATOMIC, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_LOCAL_COMM, FI_REMOTE_COMM, FI_SOURCE ]
    mode: [  ]
    addr_format: FI_SOCKADDR_IN
    src_addrlen: 16
    dest_addrlen: 0
    src_addr: fi_sockaddr_in://<removed>:50401
    dest_addr: (null)
    handle: (nil)
    fi_tx_attr:
        caps: [ FI_RMA, FI_ATOMIC, FI_READ, FI_WRITE, FI_SEND ]
        mode: [  ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_RAS, FI_ORDER_WAS, FI_ORDER_SAS, FI_ORDER_RMA_RAR, FI_ORDER_RMA_RAW, FI_ORDER_RMA_WAW, FI_ORDER_ATOMIC_RAR, FI_ORDER_ATOMIC_RAW, FI_ORDER_ATOMIC_WAW ]
        inject_size: 192
        size: 2048
        iov_limit: 4
        rma_iov_limit: 1
        tclass: 0x0
    fi_rx_attr:
        caps: [ FI_RMA, FI_ATOMIC, FI_RECV, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_SOURCE ]
        mode: [  ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_RAS, FI_ORDER_WAS, FI_ORDER_SAS, FI_ORDER_RMA_RAR, FI_ORDER_RMA_RAW, FI_ORDER_RMA_WAW, FI_ORDER_ATOMIC_RAR, FI_ORDER_ATOMIC_RAW, FI_ORDER_ATOMIC_WAW ]
        size: 2048
        iov_limit: 4
    fi_ep_attr:
        type: FI_EP_RDM
        protocol: FI_PROTO_RXM
        protocol_version: 1
        max_msg_size: 1073741824
        msg_prefix_size: 0
        max_order_raw_size: 0
        max_order_war_size: 0
        max_order_waw_size: 0
        mem_tag_format: 0xaaaaaaaaaaaaaaaa
        tx_ctx_cnt: 1
        rx_ctx_cnt: 1
        auth_key_size: 0
    fi_domain_attr:
        domain: 0x0
        name: ibp202s0
        threading: FI_THREAD_SAFE
        progress: FI_PROGRESS_AUTO
        resource_mgmt: FI_RM_ENABLED
        av_type: FI_AV_UNSPEC
        mr_mode: [ FI_MR_LOCAL, FI_MR_VIRT_ADDR, FI_MR_ALLOCATED, FI_MR_PROV_KEY ]
        mr_key_size: 4
        cq_data_size: 4
        cq_cnt: 65536
        ep_cnt: 32768
        tx_ctx_cnt: 1
        rx_ctx_cnt: 1
        max_ep_tx_ctx: 1
        max_ep_rx_ctx: 1
        max_ep_stx_ctx: 0
        max_ep_srx_ctx: 0
        cntr_cnt: 0
        mr_iov_limit: 1
        caps: [ FI_LOCAL_COMM, FI_REMOTE_COMM ]
        mode: [  ]
        auth_key_size: 0
        max_err_data: 0
        mr_cnt: 0
        tclass: 0x0
    fi_fabric_attr:
        name: IB-0xfe80000000000000
        prov_name: verbs;ofi_rxm
        prov_version: 201.0
        api_version: 2.1
    nic:
        fi_device_attr:
            <removed>
        fi_bus_attr:
            bus_type: FI_BUS_UNKNOWN
        fi_link_attr:
            address: (null)
            mtu: 4096
            speed: 100000000000
            state: FI_LINK_UP
            network_type: InfiniBand
```
**Expected behavior**
In both cases the output should look like the `FI_EP_RDM` output.

In regards to the `FI_EP_MSG` endpoint I've also tried to change the endianness of the compare values beforehand in hope to get the swaping working. Unfortunately  this didn't work either.

**Output**
See minimal example above

**Environment:**
OS: Linux
provider: verbs
Endpoint type: `FI_EP_MSG`
libfabric version: 2.1 (compiled from source)
