### ISSUE TITLE
Invalid argument binding CQ with sockets provider

### ISSUE THREAD

**Issue by disprosium8** [ofiwg/libfabric#1636]
This broke for me somewhere in the 1.2rc commits.  Currently testing with 1.2.0 tag.

I create my CQ.
```
  struct fi_cq_attr cq_attr;
  memset(&cq_attr, 0, sizeof(cq_attr));
  cq_attr.format = FI_CQ_FORMAT_DATA;
  cq_attr.wait_obj = FI_WAIT_NONE;
  cq_attr.size = fi->tx_attr->size;

...
    rc = fi_cq_open(ctx->dom, &cq_attr, &ctx->lcq[i], NULL);
```

Try to bind it.
```                                                                                                                      
  rc = fi_ep_bind(ep, &ctx->lcq[cqind]->fid, FI_READ|FI_WRITE|FI_TRANSMIT);
  if (rc) {
    dbg_err("Could not bind local CQ to self EP: %s", fi_strerror(-rc));
  }
```

and with sockets I now get:

```
ALL:ERR: 0 (__fi_connect_peers:225): > Could not bind local CQ to self EP: Invalid argument
```

Works fine with psm, and as I mentioned this used to work fine with sockets some time ago.  I'll try to find out when it broke for me.  My updated fabtests still run fine so it must be something subtle that changed.  I've been scratching my head for a while so I wanted to ask if someone could quickly enlighten me.

fi_info if that helps.
```
fi_info:
    caps: [ FI_RMA_EVENT, FI_SOURCE, FI_MSG, FI_RMA, FI_MULTI_RECV, FI_TRIGGER, FI_FENCE ]
    mode: [  ]
    addr_format: FI_SOCKADDR_IN
    src_addrlen: 16
    dest_addrlen: 16
    src_addr: 192.168.1.1
    dest_addr: 192.168.1.1
    handle: (null)
    fi_tx_attr:
        caps: [ FI_RMA_EVENT, FI_SOURCE, FI_MSG, FI_RMA, FI_MULTI_RECV, FI_TRIGGER, FI_FENCE ]
        mode: [  ]
        op_flags: [ FI_TRANSMIT_COMPLETE ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAR, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT ]
        comp_order: [  ]
        inject_size: 255
        size: 256
        iov_limit: 8
        rma_iov_limit: 8
    fi_rx_attr:
        caps: [ FI_RMA_EVENT, FI_SOURCE, FI_MSG, FI_RMA, FI_MULTI_RECV, FI_TRIGGER, FI_FENCE ]
        mode: [  ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAR, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT ]
        comp_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAR, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT, FI_ORDER_DATA ]
        total_buffered_recv: 67108864
        size: 256
        iov_limit: 8
    fi_ep_attr:
        type: FI_EP_RDM
        protocol: FI_PROTO_SOCK_TCP
        protocol_version: 1
        max_msg_size: 8388608
        msg_prefix_size: 0
        max_order_raw_size: 8388608
        max_order_war_size: 8388608
        max_order_waw_size: 8388608
        mem_tag_format: 0xaaaaaaaaaaaaaaaa
        tx_ctx_cnt: 16
        rx_ctx_cnt: 16
    fi_domain_attr:
        domain: 0x0
        name: sockets
        threading: FI_THREAD_SAFE
        control_progress: FI_PROGRESS_AUTO
        data_progress: FI_PROGRESS_AUTO
        resouce_mgmt: FI_RM_ENABLED
        av_type: FI_AV_UNSPEC
        mr_mode: FI_MR_BASIC
        mr_key_size: 8
        cq_data_size: 8
        cq_cnt: 32
        ep_cnt: 128
        tx_ctx_cnt: 16
        rx_ctx_cnt: 16
        max_ep_tx_ctx: 16
        max_ep_rx_ctx: 16
        max_ep_stx_ctx: 0
        max_ep_srx_ctx: 0
    fi_fabric_attr:
        name: IP
        prov_name: sockets
        prov_version: 1.0
```
