### ISSUE TITLE
sockets provider doesn't return correct fi_getinfo from MPICH

### ISSUE THREAD

**Issue by hppritcha** [ofiwg/libfabric#1899]
The Intel MPI folks pointed out something that doesn't seem right with info dumped from MPICH when its trying to initialize libfabric.  IN the below case, both the gni and sockets provider were found.  The application is only asking for ```FI_TAGGED``` capability.   

Here's what is dumped by mpich shortly after the fi_getinfo call:
```
mpich/examples> (topic/pmi_fixes_for_cray *)srun -n 1 ./cpi
Dumping Providers(first=0x621c10):
fi_info:
    caps: [ FI_TAGGED ]
    mode: [ FI_CONTEXT ]
    addr_format: FI_ADDR_GNI
    src_addrlen: 0
    dest_addrlen: 0
    src_addr: (null)
    dest_addr: (null)
    handle: (null)
    fi_tx_attr:
        caps: [ FI_TAGGED ]
        mode: [ FI_CONTEXT ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_SAS, FI_ORDER_STRICT ]
        comp_order: [  ]
        inject_size: 64
        size: 500
        iov_limit: 1
        rma_iov_limit: 1
    fi_rx_attr:
        caps: [ FI_TAGGED ]
        mode: [ FI_CONTEXT ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_SAS, FI_ORDER_STRICT ]
        comp_order: [  ]
        total_buffered_recv: 0
        size: 500
        iov_limit: 1
    fi_ep_attr:
        type: FI_EP_RDM
        protocol: FI_PROTO_GNI
        protocol_version: 0
        max_msg_size: 4294967295
        msg_prefix_size: 0
        max_order_raw_size: 0
        max_order_war_size: 0
        max_order_waw_size: 0
        mem_tag_format: 0x0000000000000000
        tx_ctx_cnt: 1
        rx_ctx_cnt: 1
    fi_domain_attr:
        domain: 0x0
        name: /sys/class/gni/kgni0
        threading: FI_THREAD_SAFE
        control_progress: FI_PROGRESS_AUTO
        data_progress: FI_PROGRESS_AUTO
        resouce_mgmt: FI_RM_ENABLED
        av_type: FI_AV_UNSPEC
        mr_mode: FI_MR_UNSPEC
        mr_key_size: 0
        cq_data_size: 8
        cq_cnt: 0
        ep_cnt: 0
        tx_ctx_cnt: 4
        rx_ctx_cnt: 0
        max_ep_tx_ctx: 0
        max_ep_rx_ctx: 0
        max_ep_stx_ctx: 0
        max_ep_srx_ctx: 0
    fi_fabric_attr:
        name: gni
        prov_name: gni
        prov_version: 1.0
fi_info:
    caps: [ FI_RMA_EVENT, FI_SOURCE, FI_TAGGED, FI_MULTI_RECV, FI_TRIGGER, FI_FENCE ]
    mode: [  ]
    addr_format: FI_SOCKADDR_IN
    src_addrlen: 16
    dest_addrlen: 16
    src_addr: 10.128.0.10
    dest_addr: 10.128.0.10
    handle: (null)
    fi_tx_attr:
        caps: [ FI_RMA_EVENT, FI_SOURCE, FI_TAGGED, FI_MULTI_RECV, FI_TRIGGER, FI_FENCE ]
        mode: [  ]
        op_flags: [ FI_TRANSMIT_COMPLETE ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAR, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT ]
        comp_order: [  ]
        inject_size: 255
        size: 256
        iov_limit: 8
        rma_iov_limit: 8
    fi_rx_attr:
        caps: [ FI_RMA_EVENT, FI_SOURCE, FI_TAGGED, FI_MULTI_RECV, FI_TRIGGER, FI_FENCE ]
        mode: [  ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAR, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT ]
        comp_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAR, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT, FI_ORDER_DATA ]
        total_buffered_recv: 67108864
        size: 256
        iov_limit: 8
    fi_ep_attr:
        type: FI_EP_RDM
        protocol: FI_PROTO_SOCK_TCP
        protocol_version: 1
        max_msg_size: 8388608
        msg_prefix_size: 0
        max_order_raw_size: 8388608
        max_order_war_size: 8388608
        max_order_waw_size: 8388608
        mem_tag_format: 0xaaaaaaaaaaaaaaaa
        tx_ctx_cnt: 16
        rx_ctx_cnt: 16
    fi_domain_attr:
        domain: 0x0
        name: sockets
        threading: FI_THREAD_ENDPOINT
        control_progress: FI_PROGRESS_AUTO
        data_progress: FI_PROGRESS_AUTO
        resouce_mgmt: FI_RM_ENABLED
        av_type: FI_AV_UNSPEC
        mr_mode: FI_MR_SCALABLE
        mr_key_size: 8
        cq_data_size: 8
        cq_cnt: 32
        ep_cnt: 128
        tx_ctx_cnt: 16
        rx_ctx_cnt: 16
        max_ep_tx_ctx: 16
        max_ep_rx_ctx: 16
        max_ep_stx_ctx: 0
        max_ep_srx_ctx: 0
    fi_fabric_attr:
        name: IP
        prov_name: sockets
        prov_version: 1.0
Process 0 of 1 is on nid00009
pi is approximately 3.1415926544231341, Error is 0.0000000008333410
wall clock time = 0.000106
```

The way the man page for fi_getinfo reads:
```
Interface capabilities are obtained by OR-ing the following flags
together.  If capabilities in the hint parameter are set to 0, the
underlying provider will return the set of capabilities which are
supported.  Otherwise, providers will return data matching the
specified set of capabilities.  Providers may indicate support for
additional capabilities beyond those requested when the use of
expanded capabilities will not adversely affect performance or expose
the application to communication beyond that which was requested.
Applications may use this feature to request a minimal set of
requirements, then check the returned capabilities to enable
additional optimizations.
```
the sockets provider isn't obeying the sentence "Otherwise, providers will return data matching the specified set of capabilities."
