### ISSUE TITLE
verbs: max info->tx_attr->size

### ISSUE THREAD

**Issue by tschuett** [ofiwg/libfabric#2093]
Is there a reason, why the maximum for info->tx_attr->size is so low?

```
   fi_tx_attr:
        caps: [ FI_MSG, FI_RMA, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE ]
        mode: [ FI_LOCAL_MR ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT ]
        comp_order: [  ]
        inject_size: 88
        size: 495
        iov_limit: 6
        rma_iov_limit: 1
```
This is for a Mellanox FDR card. `ibv_query_device` returns 16351 for `max_send_wr` ?!?
