### ISSUE TITLE
prov/sockets: max_msg_size from fi_info is illegal

### ISSUE THREAD

**Issue by shawnccx** [ofiwg/libfabric#4652]
'fi_info -p sockets -v' returns illegal value for 'max_msg_size', for example:

```
    fi_ep_attr:
        type: FI_EP_MSG
        protocol: FI_PROTO_SOCK_TCP
        protocol_version: 2
        max_msg_size: -4097
        msg_prefix_size: 0
        max_order_raw_size: -4097
        max_order_war_size: -4097
        max_order_waw_size: -4097
```
Current code base HEAD:

```
$ git show HEAD
commit aa2625ea2ebbbe4f74912aab2c49def155dab543 (HEAD -> master, origin/master, origin/HEAD)
Merge: b61b5f61989a f334da23f24c
Author: Automated bot for the OFIWG organization <ofiwg-bot@users.noreply.github.com>
Date:   Wed Nov 28 19:05:30 2018 -0500

    Merge pull request #4649

    More tasty nroff man pages for you, fresh out of the oven!

```
