### ISSUE TITLE
sockets provider sets dest_addr to invalid address in fi_getinfo

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#535]
I would expect that if `src_addr` or `dest_addr` is non-`NULL`, then it contains a valid address.  Instead, the sockets provider seems to unconditionally `calloc()` both, and then if `FI_SOURCE` is set or host is `NULL`, it just leaves `dest_addr` pointed to an invalid address structure.

The verbs provider appears to handle this case correctly.

**Comment by jithinjosepkl** [comment]
Sockets provider checks for src/dst addr in hints. This is after the check for FI_SOURCE/host.
Code snippet from sock_rdm_getinfo:
..
	if (hints->src_addr) {
		assert(hints->src_addrlen == sizeof(struct sockaddr_in));
		memcpy(src_addr, hints->src_addr, hints->src_addrlen);
	}

	if (hints->dest_addr) {
		assert(hints->dest_addrlen == sizeof(struct sockaddr_in));
		memcpy(dest_addr, hints->dest_addr, hints->dest_addrlen);
	}
..

Similar checks are there for DGRAM/MSG EP types.
Please let me know if this is not working as expected.

**Comment by patrickmacarthur** [comment]
I am using `FI_EP_MSG`, and both `src_addr` and `dest_addr` are `NULL` in hints.

Here is the output of `fi_tostr(&hints, FI_TYPE_INFO)`:
```YAML
fi_info:
    caps: [  ]
    mode: [ FI_LOCAL_MR, FI_PROV_MR_ATTR ]
    ep_type: FI_EP_MSG
    fi_addr_format: FI_SOCKADDR
    src_addrlen: 0
    dest_addrlen: 0
    src_addr: (null)
    dest_addr: (null)
    connreq: (null)
    fi_tx_attr: (null)
    fi_rx_attr: (null)
    fi_ep_attr: (null)
    fi_domain_attr: (null)
    fi_fabric_attr: (null)
```

And the call is just:
```C
fi_getinfo(FI_VERSION(1, 0), NULL, NULL, FI_SOURCE, &hints, &res));
```

The end result is that `src_addr` is filled with the expected contents, but `dest_addr` points to a struct filled with zeroes.  I would expect `dest_addr` to be `NULL` in this case.
