### ISSUE TITLE
verbs;ofi_rxm FI_MR_SCALABLE and FI_MR_LOCAL both being set

### ISSUE THREAD

**Issue by iziemba** [ofiwg/libfabric#5607]
The following is the output of running `fi_info -v`:

```
    fi_domain_attr:
        domain: 0x0
        name: mlx4_0
        threading: FI_THREAD_SAFE
        control_progress: FI_PROGRESS_AUTO
        data_progress: FI_PROGRESS_MANUAL
        resource_mgmt: FI_RM_ENABLED
        av_type: FI_AV_UNSPEC
        mr_mode: [ FI_MR_BASIC, FI_MR_SCALABLE, FI_MR_LOCAL, FI_MR_VIRT_ADDR, FI_MR_ALLOCATED, FI_MR_PROV_KEY ]
        mr_key_size: 4
        cq_data_size: 4
        cq_cnt: 65536
        ep_cnt: 32768
        tx_ctx_cnt: 1
        rx_ctx_cnt: 1
        max_ep_tx_ctx: 1
        max_ep_rx_ctx: 1
        max_ep_stx_ctx: 0
        max_ep_srx_ctx: 0
        cntr_cnt: 0
        mr_iov_limit: 1
    caps: [ FI_LOCAL_COMM, FI_REMOTE_COMM ]
    mode: [  ]
        auth_key_size: 0
        max_err_data: 0
        mr_cnt: 0
    fi_fabric_attr:
        name: IB-0xfe80000000000000
        prov_name: verbs;ofi_rxm
        prov_version: 1.0
        api_version: 1.9
```

Should both FI_MR_SCALABLE and FI_MR_LOCAL be set? Note that running `fi_info -p "verbs" -v` will only set FI_MR_LOCAL, FI_MR_VIRT_ADDR, FI_MR_ALLOCATED, FI_MR_PROV_KEY.
