### ISSUE TITLE
Rx and Tx caps are being expanded incorrectly

### ISSUE THREAD

**Issue by sdvormwa** [ofiwg/libfabric#5674]
In issue #5665, it was noted by @aingerson and @shefty that FI_DIRECTED_RECV | FI_RECV (and presumably also FI_REMOTE_READ | FI_REMOTE_WRITE) shouldn't be set in tx_attrs->caps and that FI_SEND (and presumably also FI_READ | FI_WRITE) shouldn't be set in rx_attrs->caps.  Should users be allowed to specify FI_MSG (similarly FI_RMA) in these?  That seems to be valid per my reading of the man-pages (and happens to be what I currently do), but breaks the assumptions from #5665 due to the fact that FI_MSG is simply FI_SEND|FI_RECV.

**Comment by aingerson** [comment]
FI_MSG and FI_RMA (as well as FI_TAGGED and FI_ATOMIC) can be either a tx or rx capability. You are correct in the sense that FI_MSG alone implies SEND | RECV but that applies only to the info->caps case. In the tx_attr and rx_attr caps, it only refers to those capability bits that are applicable in each case.

**Comment by sdvormwa** [comment]
I use fi_dupinfo() to duplicate the info returned by the provider and then the only change I make is to explicitly set tx_attrs->caps and rx_attrs->caps to 'FI_RMA|FI_MSG' and pass this new structure to fi_endpoint().  With the changes mentioned in #5665, this now fails to create an endpoint.  Are you saying that this should work?

Looking at the before and after with fi_tostr(), the only changes are that FI_RECV, FI_REMOTE_READ, FI_REMOTE_WRITE now appear in tx_attrs->caps and FI_READ, FI_WRITE, FI_SEND now appear in rx_attrs->caps.  I'm not explicitly setting those however, so something in libfabric must be.

**Comment by shefty** [comment]
Please see the updated man page for the list of rx/tx caps:
https://ofiwg.github.io/libfabric/master/man/fi_endpoint.3.html
From what you describe with FI_MSG | FI_RMA, this should work, assuming that the provider supports MSG and RMA and those caps are also listed in fi_info:caps.

I'm assuming you had the tx/rx switched in your last comment.

**Comment by shefty** [comment]
Can you provide the info:caps, tx:caps, and rx:caps for the case that used to work, but is now failing?

I want to understand if we need to ignore invalid caps, rather than rejecting them, so that we don't break existing apps.

**Comment by sdvormwa** [comment]
Here are the capabilities coming from the provider from fi_getinfo(), according to fi_tostr():

```
    caps: [ FI_MSG, FI_RMA, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_LOCAL_COMM, FI_REMOTE_COMM ]
...
    fi_tx_attr:
        caps: [ FI_MSG, FI_RMA, FI_READ, FI_WRITE, FI_SEND ]
...
    fi_rx_attr:
        caps: [ FI_MSG, FI_RMA, FI_RECV, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV ]
```

I dup this with fi_dupinfo(), and then explicitly change the capabilities to FI_MSG|FI_RMA (|FI_MULTI_RECV, if it was set originally) with

```
        hints->caps = FI_RMA | FI_MSG;
        hints->tx_attr->caps = FI_RMA | FI_MSG;
        hints->rx_attr->caps = FI_RMA | FI_MSG;
...
        if ( <provider reported FI_MULTI_RECV> ) {
            hints->caps |= FI_MULTI_RECV;
```

and the result is, again according to fi_tostr():

```
    caps: [ FI_MSG, FI_RMA, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_LOCAL_COMM, FI_REMOTE_COMM ]
...
    fi_tx_attr:
        caps: [ FI_MSG, FI_RMA, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE ]
...
   fi_rx_attr:
        caps: [ FI_MSG, FI_RMA, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV ]
```

I then pass this on to fi_endpoint().  With the changes referenced in #5665, this results in a failure to create the endpoint.
