### ISSUE TITLE
fi_info "--list" option is broken

### ISSUE THREAD

**Issue by mblockso** [ofiwg/libfabric#5945]
The "--list" options seems to return zero'd out garbage instead of the list of providers compiled into the library.

I checked out a recent master branch commit (2a686e782) and configured with these options, compiled, and installed.

> ./configure --prefix=$HOME --enable-sockets --enable-psm2 --disable-hook_debug --disable-perf --disable-rstream --disable-shm --disable-rxd --disable-mrail --disable-tcp --disable-udp --disable-efa --disable-psm --disable-rxm --disable-verbs

The `fi_info --list` output is incorrect.
```
# ~/bin/fi_info --list
psm2:
    version: 110.0
sockets:
    version: 110.0
ofi_hook_noop:
    version: 110.0
```
... "verbose" shows more zero'd out info ...
```
# ~/bin/fi_info --list -v | head -n80
---
fi_info:
    caps: [  ]
    mode: [  ]
    addr_format: FI_FORMAT_UNSPEC
    src_addrlen: 0
    dest_addrlen: 0
    src_addr: (null)
    dest_addr: (null)
    handle: (nil)
    fi_tx_attr:
        caps: [  ]
        mode: [  ]
        op_flags: [  ]
        msg_order: [  ]
        comp_order: [ FI_ORDER_NONE ]
        inject_size: 0
        size: 0
        iov_limit: 0
        rma_iov_limit: 0
    fi_rx_attr:
        caps: [  ]
        mode: [  ]
        op_flags: [  ]
        msg_order: [  ]
        comp_order: [ FI_ORDER_NONE ]
        total_buffered_recv: 0
        size: 0
        iov_limit: 0
    fi_ep_attr:
        type: FI_EP_UNSPEC
        protocol: FI_PROTO_UNSPEC
        protocol_version: 0
        max_msg_size: 0
        msg_prefix_size: 0
        max_order_raw_size: 0
        max_order_war_size: 0
        max_order_waw_size: 0
        mem_tag_format: 0x0000000000000000
        tx_ctx_cnt: 0
        rx_ctx_cnt: 0
        auth_key_size: 0
    fi_domain_attr:
        domain: 0x0
        name: (null)
        threading: FI_THREAD_UNSPEC
        control_progress: FI_PROGRESS_UNSPEC
        data_progress: FI_PROGRESS_UNSPEC
        resource_mgmt: FI_RM_UNSPEC
        av_type: FI_AV_UNSPEC
        mr_mode: [  ]
        mr_key_size: 0
        cq_data_size: 0
        cq_cnt: 0
        ep_cnt: 0
        tx_ctx_cnt: 0
        rx_ctx_cnt: 0
        max_ep_tx_ctx: 0
        max_ep_rx_ctx: 0
        max_ep_stx_ctx: 0
        max_ep_srx_ctx: 0
        cntr_cnt: 0
        mr_iov_limit: 0
    caps: [  ]
    mode: [  ]
        auth_key_size: 0
        max_err_data: 0
        mr_cnt: 0
    fi_fabric_attr:
        name: (null)
        prov_name: psm2
        prov_version: 110.0
        api_version: 0.0
    nic_fid: (nil)
---
fi_info:
    caps: [  ]
    mode: [  ]
    addr_format: FI_FORMAT_UNSPEC
    src_addrlen: 0
<snip>
```
... but "verbose" without "list" works fine:
```
# ~/bin/fi_info  -v | head -n80
---
fi_info:
    caps: [ FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_TRIGGER, FI_SOURCE_ERR, FI_LOCAL_COMM, FI_REMOTE_COMM, FI_SHARED_AV, FI_RMA_EVENT, FI_SOURCE, FI_NAMED_RX_CTX, FI_DIRECTED_RECV ]
    mode: [ FI_CONTEXT ]
    addr_format: FI_ADDR_PSMX2
    src_addrlen: 16
    dest_addrlen: 16
    src_addr: fi_addr_psmx2://ffff:2
    dest_addr: (null)
    handle: (nil)
    fi_tx_attr:
        caps: [ FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_READ, FI_WRITE, FI_SEND, FI_TRIGGER, FI_NAMED_RX_CTX ]
        mode: [ FI_CONTEXT ]
        op_flags: [ FI_MULTI_RECV, FI_TRIGGER, FI_COMPLETION, FI_INJECT, FI_INJECT_COMPLETE, FI_TRANSMIT_COMPLETE, FI_DELIVERY_COMPLETE ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_SAS, FI_ORDER_RMA_RAR, FI_ORDER_RMA_RAW, FI_ORDER_RMA_WAR, FI_ORDER_RMA_WAW, FI_ORDER_ATOMIC_RAR, FI_ORDER_ATOMIC_RAW, FI_ORDER_ATOMIC_WAR, FI_ORDER_ATOMIC_WAW ]
        comp_order: [ FI_ORDER_NONE ]
        inject_size: 64
        size: 18446744073709551615
        iov_limit: 13
        rma_iov_limit: 1
    fi_rx_attr:
        caps: [ FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_RECV, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_TRIGGER, FI_RMA_EVENT, FI_SOURCE, FI_DIRECTED_RECV ]
        mode: [ FI_CONTEXT ]
        op_flags: [ FI_MULTI_RECV, FI_TRIGGER, FI_COMPLETION, FI_INJECT, FI_INJECT_COMPLETE, FI_TRANSMIT_COMPLETE, FI_DELIVERY_COMPLETE ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_SAS, FI_ORDER_RMA_RAR, FI_ORDER_RMA_RAW, FI_ORDER_RMA_WAR, FI_ORDER_RMA_WAW, FI_ORDER_ATOMIC_RAR, FI_ORDER_ATOMIC_RAW, FI_ORDER_ATOMIC_WAR, FI_ORDER_ATOMIC_WAW ]
        comp_order: [ FI_ORDER_NONE ]
        total_buffered_recv: 18446744073709551615
        size: 18446744073709551615
        iov_limit: 1
    fi_ep_attr:
        type: FI_EP_RDM
        protocol: FI_PROTO_PSMX2
        protocol_version: 513
        max_msg_size: 4294963200
        msg_prefix_size: 0
        max_order_raw_size: 4096
        max_order_war_size: 4096
        max_order_waw_size: 4096
        mem_tag_format: 0xaaaaaaaaaaaaaaaa
        tx_ctx_cnt: 1
        rx_ctx_cnt: 1
        auth_key_size: 16
    fi_domain_attr:
        domain: 0x0
        name: hfi1_0
        threading: FI_THREAD_SAFE
        control_progress: FI_PROGRESS_MANUAL
        data_progress: FI_PROGRESS_MANUAL
        resource_mgmt: FI_RM_ENABLED
        av_type: FI_AV_UNSPEC
        mr_mode: [  ]
        mr_key_size: 8
        cq_data_size: 0
        cq_cnt: 65535
        ep_cnt: 65535
        tx_ctx_cnt: 36
        rx_ctx_cnt: 36
        max_ep_tx_ctx: 36
        max_ep_rx_ctx: 36
        max_ep_stx_ctx: 36
        max_ep_srx_ctx: 0
        cntr_cnt: 65535
        mr_iov_limit: 65535
    caps: [ FI_LOCAL_COMM, FI_REMOTE_COMM, FI_SHARED_AV ]
    mode: [  ]
        auth_key_size: 16
        max_err_data: 64
        mr_cnt: 65535
    fi_fabric_attr:
        name: psm2
        prov_name: psm2
        prov_version: 110.0
        api_version: 1.10
    fid_nic:
        fi_device_attr:
            name: (null)
            device_id: (null)
            device_version: (null)
            vendor_id: (null)
            driver: (null)
<snip>
```
