### ISSUE TITLE
[OFI 1.12.0] fi_info -l present providers which are not exists at all

### ISSUE THREAD

**Issue by danielap1996** [ofiwg/libfabric#9649]
**Describe the bug**
As you can see while running fi_info -l (v 1.12.0) we can see the verbs provider:
```

root@6dc00c545af3:~/habanaqa_topologies# fi_info --version
fi_info: 1.20.0
libfabric: 1.20.0
libfabric api: 1.20

oot@6dc00c545af3:~/habanaqa_topologies# fi_info -l
usnic:
    version: 1.0
verbs:
    version: 120.0
ofi_rxm:
    version: 120.0
ofi_rxd:
    version: 120.0
shm:
    version: 120.0
udp:
    version: 120.0
tcp:
    version: 120.0
sockets:
    version: 120.0
ofi_hook_perf:
    version: 120.0
ofi_hook_trace:
    version: 120.0
ofi_hook_debug:
    version: 120.0
ofi_hook_noop:
    version: 120.0
ofi_hook_hmem:
    version: 120.0
ofi_hook_dmabuf_peer_mem:
    version: 120.0
off_coll:
    version: 120.0
sm2:
    version: 120.0
ofi_mrail:
    version: 120.0

```

**Expected behavior**
while using OFI 1.19.0, as you can see, we don't have the verbs provider (which is the correct behavior)

```
root@a268e4c28cbd:~/habanaqa_topologies# fi_info --version
fi_info: 1.19.0amzn3.0
libfabric: 1.19.0amzn3.0
libfabric api: 1.19
root@a268e4c28cbd:~/habanaqa_topologies# fi_info -l
ofi_rxm:
    version: 119.0
shm:
    version: 119.0
udp:
    version: 119.0
tcp:
    version: 119.0
sockets:
    version: 119.0
ofi_hook_perf:
    version: 119.0
ofi_hook_trace:
    version: 119.0
ofi_hook_profile:
    version: 119.0
ofi_hook_debug:
    version: 119.0
ofi_hook_noop:
    version: 119.0
ofi_hook_hmem:
    version: 119.0
ofi_hook_dmabuf_peer_mem:
    version: 119.0
off_coll:
    version: 119.0
sm2:
    version: 119.0
ofi_mrail:
    version: 119.0

```

just in case:
in both of the cases I was running from an container of ubunto20.04 OS that was launched on VM
both the images were built the same, but in one of them we installed OFI 1.19 and in the 2nd one we installed OFI 1.20
